[2023-03-17T10:52:17.526+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:52:06.095718+00:00 [queued]>
[2023-03-17T10:52:17.533+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:52:06.095718+00:00 [queued]>
[2023-03-17T10:52:17.534+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:52:17.534+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-17T10:52:17.534+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:52:17.545+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest> on 2023-03-17 10:52:06.095718+00:00
[2023-03-17T10:52:17.548+0000] {standard_task_runner.py:55} INFO - Started process 3080 to run task
[2023-03-17T10:52:17.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2023-03-17T10:52:06.095718+00:00', '--job-id', '1787', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpj_b6t5p5']
[2023-03-17T10:52:17.552+0000] {standard_task_runner.py:83} INFO - Job 1787: Subtask ingest
[2023-03-17T10:52:17.560+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-17T10:52:17.594+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:52:06.095718+00:00 [running]> on host 846854af4045
[2023-03-17T10:52:17.623+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-03-17T10:52:17.652+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T10:52:06.095718+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T10:52:06.095718+00:00
[2023-03-17T10:52:17.653+0000] {logging_mixin.py:137} INFO - yellow_tax_2023_03 /opt/***/output_2023-03.csv 2023-03-17T10:52:06.095718+00:00
[2023-03-17T10:52:17.658+0000] {ingestion_script.py:12} INFO - connected to ny_taxi
[2023-03-17T10:52:17.662+0000] {ingestion_script.py:19} INFO - starting to ingest data
[2023-03-17T10:52:17.715+0000] {ingestion_script.py:24} INFO - Insert the first chunk
[2023-03-17T10:52:17.715+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion_script.py", line 28, in ingest_callable
    df = next(df_iter)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1024, in __next__
    return self.get_chunk()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1074, in get_chunk
    return self.read(nrows=size)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 229, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 783, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader._read_rows
StopIteration
[2023-03-17T10:52:17.721+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20230317T105206, start_date=20230317T105217, end_date=20230317T105217
[2023-03-17T10:52:17.730+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1787 for task ingest (; 3080)
[2023-03-17T10:52:17.762+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T10:52:17.775+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
