[2023-03-17T10:44:20.947+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:44:17.639996+00:00 [queued]>
[2023-03-17T10:44:20.955+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:44:17.639996+00:00 [queued]>
[2023-03-17T10:44:20.956+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:44:20.956+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-17T10:44:20.956+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:44:20.967+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest> on 2023-03-17 10:44:17.639996+00:00
[2023-03-17T10:44:20.972+0000] {standard_task_runner.py:55} INFO - Started process 2397 to run task
[2023-03-17T10:44:20.974+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2023-03-17T10:44:17.639996+00:00', '--job-id', '1778', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpv88stcwd']
[2023-03-17T10:44:20.975+0000] {standard_task_runner.py:83} INFO - Job 1778: Subtask ingest
[2023-03-17T10:44:20.985+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-17T10:44:21.050+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:44:17.639996+00:00 [running]> on host 846854af4045
[2023-03-17T10:44:21.100+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-03-17T10:44:21.138+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T10:44:17.639996+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T10:44:17.639996+00:00
[2023-03-17T10:44:21.139+0000] {logging_mixin.py:137} WARNING - --- Logging error ---
[2023-03-17T10:44:21.141+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-03-17T10:44:21.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2023-03-17T10:44:21.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2023-03-17T10:44:21.141+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2023-03-17T10:44:21.142+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2023-03-17T10:44:21.142+0000] {logging_mixin.py:137} WARNING - TypeError: not all arguments converted during string formatting
[2023-03-17T10:44:21.142+0000] {logging_mixin.py:137} WARNING - Call stack:
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 39, in main
    args.func(args)
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 200, in worker
    celery_app.worker_main(options)
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2023-03-17T10:44:21.152+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 351, in worker
    worker.start()
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 115, in on_start
    **self.options)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-03-17T10:44:21.153+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in fast_trace_task
    uuid, args, kwargs, request,
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-03-17T10:44:21.154+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 96, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 130, in _execute_in_fork
    args.func(args)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 395, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 193, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 252, in _run_task_by_local_task_job
    run_job.run()
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 258, in run
    self._execute()
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 151, in _execute
    self.task_runner.start()
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 43, in start
    self.process = self._start_by_fork()
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 95, in _start_by_fork
    args.func(args, dag=self.dag)
[2023-03-17T10:44:21.155+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 395, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 195, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 272, in _run_raw_task
    pool=args.pool,
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1520, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1581, in _execute_task
    result = execute_callable(context=context)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/opt/***/dags/ingestion_script.py", line 8, in ingest_callable
    logging.info(table_name, csv_file)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2023-03-17T10:44:21.156+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2023-03-17T10:44:21.157+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2023-03-17T10:44:21.157+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2023-03-17T10:44:21.157+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2023-03-17T10:44:21.157+0000] {logging_mixin.py:137} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 80, in emit
    self.handler.emit(record)
[2023-03-17T10:44:21.157+0000] {logging_mixin.py:137} WARNING - Message: 'yellow_tax_2023_03'
Arguments: ('/opt/***/output_2023-03.csv',)
[2023-03-17T10:44:21.162+0000] {ingestion_script.py:12} INFO - connected to ny_taxi
[2023-03-17T10:44:21.174+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion_script.py", line 16, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2023-03-17T10:44:21.183+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20230317T104417, start_date=20230317T104420, end_date=20230317T104421
[2023-03-17T10:44:21.193+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1778 for task ingest ('DataFrame' object has no attribute 'tpep_pickup_datetime'; 2397)
[2023-03-17T10:44:21.226+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T10:44:21.240+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
