[2023-03-17T11:15:54.995+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T11:15:52.194083+00:00 [queued]>
[2023-03-17T11:15:55.002+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T11:15:52.194083+00:00 [queued]>
[2023-03-17T11:15:55.002+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T11:15:55.003+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-17T11:15:55.003+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T11:15:55.013+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest> on 2023-03-17 11:15:52.194083+00:00
[2023-03-17T11:15:55.017+0000] {standard_task_runner.py:55} INFO - Started process 5057 to run task
[2023-03-17T11:15:55.020+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2023-03-17T11:15:52.194083+00:00', '--job-id', '1801', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp1c_q_cp0']
[2023-03-17T11:15:55.021+0000] {standard_task_runner.py:83} INFO - Job 1801: Subtask ingest
[2023-03-17T11:15:55.029+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-17T11:15:55.063+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T11:15:52.194083+00:00 [running]> on host 846854af4045
[2023-03-17T11:15:55.089+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-03-17T11:15:55.118+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T11:15:52.194083+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T11:15:52.194083+00:00
[2023-03-17T11:15:55.119+0000] {logging_mixin.py:137} INFO - yellow_tax_2023_03 /opt/***/output_2023-03.csv.gz 2023-03-17T11:15:52.194083+00:00
[2023-03-17T11:15:55.129+0000] {ingestion_script.py:12} INFO - connected to ny_taxi
[2023-03-17T11:15:55.131+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion_script.py", line 14, in ingest_callable
    df_iter = pd.read_csv(csv_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
  File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'No')
[2023-03-17T11:15:55.139+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20230317T111552, start_date=20230317T111554, end_date=20230317T111555
[2023-03-17T11:15:55.147+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1801 for task ingest (Not a gzipped file (b'No'); 5057)
[2023-03-17T11:15:55.191+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T11:15:55.233+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
